### ISSUE TITLE
redPdaq crashes on startup

### ISSUE THREAD

**Issue by JulianBaader** [GuenterQuast/redpitaya-daq#1]
Traceback (most recent call last):
  File "/home/julian/git/coincidence/redPdaq.py", line 317, in closeEvent
    self.stop()
  File "/home/julian/git/coincidence/redPdaq.py", line 311, in stop
    self.connectButton.clicked.connect(self.start)
                                       ^^^^^^^^^^
AttributeError: 'rpControl' object has no attribute 'start'. Did you mean: 'startIO'?

**changing 'start' to 'startIO' seems to fix it**

**Comment by GuenterQuast** [comment]
indeed - fixed !
